---
title: "Simulating survival data under the YP model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulating survival data under the YP model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(YPPE)
```



```{r covariates}

# fixing the seed for the rng:
set.seed(1234567890)

gamma <- c(1.5, 1);  # shape and scale parameters
n <- 100

# generating the set of explanatory variables:
covariates <- data.frame(
  trt = rbinom(n, 1, 0.5),
  age = rnorm(n)
)

```

## Proportional hazards random generation

```{r}
# generating the data set:
simdata <- rsurv(
  ~ trt + age, covariates = covariates,
  baseline = "weibull",
  gamma = gamma,
  psi = c(2, -1),
  phi = c(2, -1),
  max_fu = 5
)

ph <- phpe(Surv(time, status)~trt+age, data = simdata, n_int = 10, init = 0)
po <- pope(Surv(time, status)~trt+age, data = simdata, n_int = 10, init = 0)
yp <- yppe(Surv(time, status)~trt+age, data = simdata, n_int = 10, init = 0)
anova(ph, po, yp)

```


## Proportional odds random generation

```{r, po}
# generating the data set:
simdata <- rsurv(
  ~ trt + age, covariates = covariates,
  baseline = "weibull",
  gamma = gamma,
  psi = c(2, -1),
  phi = c(0, 0),
  max_fu = 5
)

ph <- phpe(Surv(time, status)~trt+age, data = simdata, n_int = 10, init = 0)
po <- pope(Surv(time, status)~trt+age, data = simdata, n_int = 10, init = 0)
yp <- yppe(Surv(time, status)~trt+age, data = simdata, n_int = 10, init = 0)
anova(ph, po, yp)

```

## Yang and Prentice random generation

```{r, yp}
# generating the data set:
simdata <- rsurv(
  ~ trt + age, covariates = covariates,
  baseline = "weibull",
  gamma = gamma,
  psi = c(2, -1),
  phi = c(-1, -1),
  max_fu = 5
)

ph <- phpe(Surv(time, status)~trt+age, data = simdata, n_int = 10, init = 0)
po <- pope(Surv(time, status)~trt+age, data = simdata, n_int = 10, init = 0)
yp <- yppe(Surv(time, status)~trt+age, data = simdata, n_int = 10, init = 0)
anova(ph, po, yp)

```

